[general]

[[sources]]
type = "rssfeed"
name = "reddit news"
[sources.options]
url = "https://www.reddit.com/r/news.rss"

[[sources]]
type = "rssfeed"
name = "Slashdot"
[sources.options]
url = "http://rss.slashdot.org/Slashdot/slashdotMain"
fields = "title,description"


[[sources]]
type = "textfile"
name = "The configuration"
[sources.options]
filepath = "config.toml"

[[sources]]
name  = "SeaTac International Airport weather report"
type = "weather"
[sources.options]
station  = "KSEA"

[[sources]]
name = "Washington state weather alerts"
type = "weatheralert"
[sources.options]
state = "WA"


[[sources]]
name = "fortune"
type = "command"
[sources.options]
command = "fortune"
